### ISSUE TITLE
Unable to install latest version of SAM

### ISSUE THREAD

**Issue by shivushedad** [aws-actions/setup-sam#52] opened 2022-07-31 12:05 UTC
We were trying to update EphemeralStorage on our Serverless function.

This is supposed to work based on https://github.com/aws/serverless-application-model/issues/2361 and documentation [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-ephemeralstorage).

However, on our GHA workflow when using latest setup-sam action, it only installs 1.41. Due to this down the line when using SAM deploy we get an error `property EphemeralStorage not defined for resource of type AWS::Serverless::Function` (which per the documentation should be valid)

Workflow step:
```
- name: Setup AWS SAM
  uses: aws-actions/setup-sam@v2
```

![image](https://user-images.githubusercontent.com/29564211/182025372-5a518138-cae1-4259-9b86-2ebf1811b095.png)

We also tried to use the [version](https://github.com/aws-actions/setup-sam/blob/main/action.yml#L7) parameter to force it to download version 1.48 and got this error:
![image](https://user-images.githubusercontent.com/29564211/182025466-26e42ae6-a6bd-46b4-8f42-3f5a6c79165e.png)

**Comment by hoffa** [comment] 2022-08-02 21:18
Are you using a self-hosted runner? Perhaps it's using a PyPI mirror that doesn't include the latest versions?

The versions are there in the public repository:

```bash
% pip install aws-sam-cli==
ERROR: Could not find a version that satisfies the requirement aws-sam-cli== (from versions: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.21.0, 0.22.0, 0.23.0, 0.30.0, 0.31.0, 0.31.1, 0.32.0, 0.33.1, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.39.0, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.46.1, 0.46.2, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.2, 1.4.0, 1.6.0, 1.6.2, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.19.1, 1.20.0, 1.21.0, 1.21.1, 1.22.0, 1.23.0, 1.24.0, 1.24.1, 1.25.0, 1.26.0, 1.27.0, 1.27.1, 1.27.2, 1.28.0, 1.29.0, 1.30.0, 1.31.0, 1.32.0, 1.33.0, 1.34.1, 1.35.0, 1.36.0, 1.37.0, 1.38.0, 1.38.1, 1.39.0, 1.40.0, 1.40.1, 1.41.0, 1.42.0, 1.43.0, 1.44.0, 1.45.0, 1.46.0, 1.47.0, 1.48.0, 1.49.0, 1.50.0, 1.51.0, 1.52.0, 1.53.0)
```

**Comment by shivushedad** [comment] 2022-08-02 22:26
> Are you using a self-hosted runner? Perhaps it's using a PyPI mirror that doesn't include the latest versions?
> 
> The versions are there in the public repository:
> 
> ```shell
> % pip install aws-sam-cli==
> ERROR: Could not find a version that satisfies the requirement aws-sam-cli== (from versions: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.21.0, 0.22.0, 0.23.0, 0.30.0, 0.31.0, 0.31.1, 0.32.0, 0.33.1, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.39.0, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.46.1, 0.46.2, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.2, 1.4.0, 1.6.0, 1.6.2, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.19.1, 1.20.0, 1.21.0, 1.21.1, 1.22.0, 1.23.0, 1.24.0, 1.24.1, 1.25.0, 1.26.0, 1.27.0, 1.27.1, 1.27.2, 1.28.0, 1.29.0, 1.30.0, 1.31.0, 1.32.0, 1.33.0, 1.34.1, 1.35.0, 1.36.0, 1.37.0, 1.38.0, 1.38.1, 1.39.0, 1.40.0, 1.40.1, 1.41.0, 1.42.0, 1.43.0, 1.44.0, 1.45.0, 1.46.0, 1.47.0, 1.48.0, 1.49.0, 1.50.0, 1.51.0, 1.52.0, 1.53.0)
> ```

Yes we are using self hosted runners as we are behind a corporate network.

**Comment by hoffa** [comment] 2022-08-03 22:33
Okay, I'm assuming the issue is due to using a PyPI mirror that doesn't include latest package versions, in which case you'll have to ask the repository admins to update.

You can confirm by checking that `pip.conf` (you can get the list of locations by running `pip config list -v`) overrides the default PyPI repository.

**Comment by hoffa** [comment] 2022-09-01 20:40
Closing this, assuming issue was with using a non-default PyPI mirror in the runner. Let me know if the issue persists.

**Closed by hoffa** 2022-09-01 20:40 UTC
