### ISSUE TITLE
Error: Getting requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by cc-simon** [aws-actions/setup-sam#82] opened 2023-07-17 15:57 UTC
The setup-sam@v2 build action is failing all our pipelines 

the error message is-
 Getting requirements to build wheel did not run successfully

I get the following stack trace

`exit code: 1
  ╰─> [68 lines of output]
      /tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/runner/work/_temp/setup-sam-ga5CTW/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/runner/work/_temp/setup-sam-ga5CTW/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/_temp/setup-sam-ga5CTW/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1[234](https://github.com/CloudCall-Engineering/syncconnectors-bullhorn/actions/runs/5577482690/jobs/10190902096#step:4:238), in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line [251](https://github.com/CloudCall-Engineering/syncconnectors-bullhorn/actions/runs/5577482690/jobs/10190902096#step:4:255), in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-w2zxlt4k/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: The process '/home/runner/work/_temp/setup-sam-ga5CTW/.venv/bin/python' failed with exit code 1`

**Comment by justinwb** [comment] 2023-07-17 15:57
Can also confirm that I'm now seeing the same behavior

**Comment by hiramhuang** [comment] 2023-07-17 15:59
Same issue here

**Comment by CesarCarrillo91** [comment] 2023-07-17 16:00
Same here.

**Comment by cortex** [comment] 2023-07-17 16:32
I had the same problem, enabling use-installer made it work for me:
```
      - uses: aws-actions/setup-sam@v2
        with:
            use-installer: true
```

**Comment by 2andrew** [comment] 2023-07-17 16:34
I had the same problem when running `pip install awscli` and adding this line helped me:
`pip3 install pyyaml==5.3.1 `

**Comment by cc-simon** [comment] 2023-07-17 17:05
> I was already running with the `use-installer` parameter set to true - so I can confirm that at least for me, that is not a fix.
> 
> 
> 
> > I had the same problem, enabling use-installer made it work for me:
> 
> > 
> 
> > ```
> 
> >       - uses: aws-actions/setup-sam@v2
> 
> >         with:
> 
> >             use-installer: true
> 
> > ```
> 
> 
> 
> 

Same I tried this too, it didn't help

**Comment by gastonsilva** [comment] 2023-07-17 17:27
https://github.com/yaml/pyyaml/issues/724
https://github.com/yaml/pyyaml/issues/601

**Comment by arantesxyz** [comment] 2023-07-17 18:37
Same!

**Comment by DanskySantos** [comment] 2023-07-17 19:44
$ pip install awscli
Collecting awscli
  Obtaining dependency information for awscli from https://files.pythonhosted.org/packages/43/9c/bf16d97f5de8aa4f9171c6c82bad0b[41](https://gitlab.com/blue-tech/crediblue-api/-/jobs/4671359200#L41)79921ddca5066ba980358da0e9a5/awscli-1.29.3-py3-none-any.whl.metadata
  Downloading awscli-1.29.3-py3-none-any.whl.metadata (11 kB)
Collecting botocore==1.31.3 (from awscli)
  Obtaining dependency information for botocore==1.31.3 from https://files.pythonhosted.org/packages/b0/f0/5755508b3305534cd4cf2a8a82bbbe[42](https://gitlab.com/blue-tech/crediblue-api/-/jobs/4671359200#L42)ee9d66fd2688be5ff3dfb85e9a99/botocore-1.31.3-py3-none-any.whl.metadata
  Downloading botocore-1.31.3-py3-none-any.whl.metadata (5.9 kB)
Collecting docutils<0.17,>=0.10 (from awscli)
  Downloading docutils-0.16-py2.py3-none-any.whl (5[48](https://gitlab.com/blue-tech/crediblue-api/-/jobs/4671359200#L48) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.2/548.2 kB 9.5 MB/s eta 0:00:00
Collecting s3transfer<0.7.0,>=0.6.0 (from awscli)
  Downloading s3transfer-0.6.1-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 10.5 MB/s eta 0:00:00
Collecting PyYAML<5.5,>=3.10 (from awscli)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 24.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 5[51](https://gitlab.com/blue-tech/crediblue-api/-/jobs/4671359200#L51), in run
          self.add_defaults()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line [58](https://gitlab.com/blue-tech/crediblue-api/-/jobs/4671359200#L58)9, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-isnoxeh9/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line [107](https://gitlab.com/blue-tech/crediblue-api/-/jobs/4671359200#L107), in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1

**Comment by hoffa** [comment] 2023-07-17 23:27
FYI if you're not using `use-installer`, you can override PyPI dependency versions with e.g. https://github.com/aws-actions/setup-sam/issues/64#issuecomment-1368755583 or https://github.com/aws-actions/setup-sam/issues/64#issuecomment-1369724002.

Also could someone that has `use-installer: true` post what is the error message and at what step does it happen? `use-installer` doesn't use PyPI or `pip` at all, so it's not clear to me why it wouldn't work.

**Comment by hawflau** [comment] 2023-07-17 23:49
As for the [workaround](https://github.com/aws-actions/setup-sam/issues/82#issuecomment-1639029986), please pin PyYAML to 5.4.1, because of the requirements of SAM CLI and its dependencies.

@hoffa However, I don't fully understand - Can customer specify which Python version to use in this GH Action? AFAIK, it's only breaking when Python version is 3.10+

**Comment by hoffa** [comment] 2023-07-18 00:04
> @hoffa However, I don't fully understand - Can customer specify which Python version to use in this GH Action? AFAIK, it's only breaking when Python version is 3.10+

If using the recommend `use-installer: true`, it uses the native installers, skipping the separate Python interpreter and PyPI altogether.

Without it, the Python interpreter can be specified with the [`python` option](https://github.com/aws-actions/setup-sam#python).

**Comment by hamzashabbir11** [comment] 2023-07-18 07:28
Tried all the Above Fixes. None of them Worked for me. I am using sam@v1
`- uses: aws-actions/setup-sam@v2`

**Comment by LinoyMKunjappan** [comment] 2023-07-18 10:01
The version setup-sam@v1 doesn't recognize the use-installer but v2 does and is working for me
```
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
```

**Comment by jay-patel-simformsolutions** [comment] 2023-07-18 12:17
+1, Need help

**Comment by mik3fly** [comment] 2023-07-18 13:19
pLeAsE HeLp

**Comment by hoffa** [comment] 2023-07-18 13:55
https://github.com/aws-actions/setup-sam/pull/83 is merged and should now work.

Also could someone for who https://github.com/aws-actions/setup-sam/issues/82#issuecomment-1638483497 did _not_ work provide some more information:

> Also could someone that has `use-installer: true` post what is the error message and at what step does it happen? `use-installer` doesn't use PyPI or `pip` at all, so it's not clear to me why it wouldn't work.

We haven't been able to reproduce, so that information could help us improve.

**Comment by hamzashabbir11** [comment] 2023-07-18 16:13
Still Not Working

**Comment by hamzashabbir11** [comment] 2023-07-18 16:22
```
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
```

<img width="923" alt="image" src="https://github.com/aws-actions/setup-sam/assets/62654154/12edd986-9a93-4e0b-959c-774fcfbb9824">



This is my Error and Code Snippet for Pipeline. Okay so I am using v1. Let me upgrade it to v2.

**Comment by mik3fly** [comment] 2023-07-18 16:33
working on aws-actions/setup-sam@main and @v2 for me

**Comment by KhanjanMarthak** [comment] 2023-07-18 16:35
Working with v2. Code has been Updated 2hours ago.

**Comment by hoffa** [comment] 2023-07-18 16:38
Thanks for confirming and for your patience, closing now. If any issues persist, please open a new issue.

---

All, please make sure you're using `v2`.

Also, I highly recommend adding `use-installer: true` going forward:

```yaml
  - uses: aws-actions/setup-sam@v2
    with:
        use-installer: true
```

It will make installation a lot faster, it doesn't use PyPI (hence not impacted by sudden transient dependency changes such as this), and doesn't require a separate Python installation (i.e. you can get rid of `actions/setup-python` if you only used it for `aws-actions/setup-sam`).

**Closed by hoffa** 2023-07-18 16:38 UTC
Labels: bug, dependencies

**Comment by hamzashabbir11** [comment] 2023-07-19 07:04
`Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/opt/hostedtoolcache/Python/3.7.17/x64/bin/python', '/opt/hostedtoolcache/Python/3.7.17/x64/python', '/usr/bin/python', '/bin/python', '/opt/hostedtoolcache/Python/3.7.17/x64/bin/python3', '/usr/bin/python3', '/bin/python3'] which did not satisfy constraints for runtime: python3.8. Do you have python for runtime: python3.8 on your PATH?`

Getting this Error.

**Comment by hoffa** [comment] 2023-07-19 15:28
@hamzashabbir11 Make sure you have Python 3.8 installed.

**Comment by aron-radvanyi** [comment] 2023-07-19 19:34
![image](https://github.com/aws-actions/setup-sam/assets/108479744/7bfb6599-8dd4-41d0-adb8-3c5ac5a741f9)

Install the PyYAML 5.3.1 and then run pip install rasa. That works currently solving the PyYAML-5.4.1.tar.gz error until they update at Rasa.

Just run: pip install PyYAML==5.3.1 pip install rasa

**Comment by pererasu** [comment] 2023-10-25 05:33
Reverting back to pyyaml 5.4.1 worked for me. Was trying to go to 6.0.1.

**Comment by Jonaid97** [comment] 2023-12-17 14:47
I've also got the same error while pip pulse2percept. Can anyone also encounters the same error please help how to resolve it?
