### ISSUE TITLE
jsonschema new patch version breaks the deployment

### ISSUE THREAD

**Issue by ehsankhfr-edf** [aws-actions/setup-sam#80] opened 2023-07-12 12:12 UTC
I have been facing with new issues while using this GA today, as a new version of jsonschema (`4.18.1`) has been released just today, which makes my deployment to fail:

<img width="933" alt="Screenshot 2023-07-12 at 13 10 50" src="https://github.com/aws-actions/setup-sam/assets/107119566/881a39d5-79e9-4dd4-a857-9622a4dec30b">

And, I think your GA should pin down the version for that package to `4.18.0`.

**Comment by hoffa** [comment] 2023-07-12 14:12
Can you try by adding [`use-installer: true`](https://github.com/aws-actions/setup-sam#use-installer) to the action options?

It'll use the prepackaged installers directly, bypassing PyPI altogether.

**Comment by hoffa** [comment] 2023-07-12 19:24
Might be related? https://github.com/python-jsonschema/jsonschema/issues/1124

A new `4.18.2` was released which fixes a regression: https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst

**Comment by hoffa** [comment] 2023-07-12 19:27
Closing as the regression seems to be fixed. Let me know if it doesn't work. In any case I would recommend using `use-installer: true` to avoid these sort of issues in the future.

**Closed by hoffa** 2023-07-12 19:27 UTC
